name = "BrickLink"
uuid = "cb7cc1ea-ba4f-478c-9ead-e901ff9c7556"
authors = ["Bernhard König <github@diro.ch> and contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1.6.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
